"""AUTH Module - Identity management, JWT lifecycle, password flows, and RBAC engine."""

from .service import (
    signup,
    verify_email,
    login,
    refresh,
    logout,
    forgot_password,
    reset_password,
    me,
    issue_access_token,
    verify_access_token,
    hash_password,
    verify_password,
    password_policy,
    rbac_can,
    require_roles,
    auth_hook,
    invalidate_user_sessions,
    change_role,
    deactivate_user,
    sweep_expired_tokens,
    AuthService,
    AuthRouter,
)

__all__ = [
    "signup",
    "verify_email",
    "login",
    "refresh",
    "logout",
    "forgot_password",
    "reset_password",
    "me",
    "issue_access_token",
    "verify_access_token",
    "hash_password",
    "verify_password",
    "password_policy",
    "rbac_can",
    "require_roles",
    "auth_hook",
    "invalidate_user_sessions",
    "change_role",
    "deactivate_user",
    "sweep_expired_tokens",
    "AuthService",
    "AuthRouter",
]
